name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Cài đặt Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Cài đặt Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build image bằng docker-compose
    - name: Build Docker image with docker-compose
      run: |
        docker-compose -f docker-compose.yml build

    # Tag image để chuẩn bị push
    - name: Tag Docker image
      run: |
        docker tag docshareapi:latest ${{ secrets.DOCKER_USERNAME }}/docshareapi:latest

    # Push image lên Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/docshareapi:latest
