name: Build, Push, and Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout mã nguồn
    - name: Checkout code
      uses: actions/checkout@v3

    # Cài đặt Docker và Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Đăng nhập Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build image
    - name: Build Docker image with docker-compose
      run: |
        docker-compose -f docker-compose.yml build

    # Tag image
    - name: Tag Docker image
      run: |
        docker tag docshareapi:latest ${{ secrets.DOCKER_USERNAME }}/docshareapi:${{ github.sha }}
        docker tag docshareapi:latest ${{ secrets.DOCKER_USERNAME }}/docshareapi:latest

    # Push image
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/docshareapi:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/docshareapi:latest

    # Trigger Render Deploy
    - name: Trigger Render Deploy
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{}' ${{ secrets.RENDER_DEPLOY_HOOK }}
      if: success()
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
