name: Build and Push Docker Image

# Khi nào workflow sẽ chạy
on:
  push:
    branches:
      - master  # Thay đổi nhánh nếu cần (ví dụ: master)
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code từ repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List files for debugging
      run: ls -la
      working-directory: ./DocShareAPI  # Kiểm tra file trong thư mục DocShareAPI
      
    # Đăng nhập vào Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build và push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./DocShareAPI  # Thư mục chứa Dockerfile
        file: ./DocShareAPI/Dockerfile  # Đường dẫn chính xác tới Dockerfile
        push: true  # Push lên Docker Hub
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/documentshareapi:latest
          ${{ secrets.DOCKER_USERNAME }}/documentshareapi:${{ github.sha }}

    # (Tùy chọn) In thông tin image đã push
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
